version: '2.2'
services:
  elasticsearch:
    image: elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
      # - node.name=es01
      # - cluster.name=es-docker-cluster
      # - discovery.seed_hosts=es02,es03
      # - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    # volumes:
    #   - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: kibana:7.14.1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - elastic

#    logstash:
#     image: logstash:8.3.1
#     container_name: logstash
#     ports:
#       - 5044:5044
#     volumes:
#       # - ./clickstream.conf:/home/svetlana/elk_homework/elk_demo/elk_demo/logstash/clickstream.conf
#       # - ./cluster-ca-certificate.pem:/usr/share/logstash/cluster-ca-certificate.pem
#       - ./config/pipelines.yml:/home/svetlana/elk_homework/elk_demo/elk_demo/logstash/pipelines.yml:ro
#       - ./config/pipelines:/home/svetlana/elk_homework/elk_demo/elk_demo/logstash/pipelines:ro
#       - ./logs:/home/svetlana/elk_homework/elk_demo/elk_demo/logstash/input
    networks:
      - elastic
networks:
  elastic:
    driver: bridge